repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^api/
      - id: ruff-format
        files: ^api/

  - repo: local
    hooks:
      - id: pylint-pipeline
        name: pylint (pipeline)
        entry: pipeline/.venv/bin/pylint
        language: system
        types: [python]
        files: ^pipeline/
        args: ["--rcfile=pipeline/.pylintrc"]

      - id: pylint-api
        name: pylint (api)
        entry: api/.venv/bin/pylint
        language: system
        types: [python]
        files: ^api/
        args: ["--rcfile=api/pyproject.toml"]
